
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import tkinter as tk
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from SMS import SMS
from CALLS import TakeACall


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C://Users/ilias/Documents/GitHub/Virtual_Assistant/MainGui/assets_5/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def CALLSMS():
    window = tk.Toplevel()

    window.geometry("526x600")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 600,
        width = 526,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        0.0,
        0.0,
        526.0,
        80.0,
        fill="#25487C",
        outline="")

    canvas.create_text(
        92.0,
        15.0,
        anchor="nw",
        text="Calls & SMS",
        fill="#201313",
        font=("MontserratRoman SemiBold", 32 * -1)
    )

    canvas.create_rectangle(
        0.0,
        80.0,
        526.0,
        601.0,
        fill="#D9D9D9",
        outline="")

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(canvas,
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=TakeACall,
        relief="flat"
    )
    button_1.place(
        x=27.0,
        y=251.0,
        width=210.0,
        height=78.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(canvas,
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=SMS,
        relief="flat"
    )
    button_2.place(
        x=263.0,
        y=251.0,
        width=220.0,
        height=78.0
    )

    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        58.0,
        43.0,
        image=image_image_1
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    image_2 = canvas.create_image(
        42.0,
        33.0,
        image=image_image_2
    )
    window.resizable(False, False)
    window.mainloop()
