
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import tkinter as tk
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C://Users/ilias/Documents/GitHub/Virtual_Assistant/MainGui/assets_4/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def SendEmail():
    sender = entry_1.get()
    receiver = entry_2.get()
    if not sender:
        messagebox.showerror('Error','the mail has neither sender nor receiver')
    elif not receiver:
        messagebox.showerror('Error','the mail has neither sender nor receiver')
    else:
        messagebox.showinfo('Send','The mail has been send Succesfully')

def Mail():
    window = tk.Toplevel()

    window.geometry("509x617")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 617,
        width = 509,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        0.0,
        0.0,
        509.0,
        81.18421173095703,
        fill="#25487C",
        outline="")

    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        255.0,
        40.0,
        image=image_image_1
    )

    canvas.create_rectangle(
        0.0,
        80.0,
        509.0,
        617.0,
        fill="#9198BF",
        outline="")

    canvas.create_text(
        5.0,
        85.0,
        anchor="nw",
        text="FROM:",
        fill="#0C0A0A",
        font=("MontserratRoman Regular", 20 * -1)
    )

    canvas.create_text(
        5.0,
        155.0,
        anchor="nw",
        text="TO:",
        fill="#0C0A0A",
        font=("MontserratRoman Regular", 20 * -1)
    )

    canvas.create_text(
        5.0,
        225.0,
        anchor="nw",
        text="SUBJECT:",
        fill="#0C0A0A",
        font=("MontserratRoman Regular", 20 * -1)
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        302.5,
        109.0,
        image=entry_image_1
    )
    global entry_1
    global entry_2
    entry_1 = Entry(canvas,
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=117.0,
        y=88.0,
        width=371.0,
        height=40.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        302.5,
        179.0,
        image=entry_image_2
    )
    entry_2 = Entry(canvas,
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_2.place(
        x=117.0,
        y=158.0,
        width=371.0,
        height=40.0
    )

    entry_image_3 = PhotoImage(
        file=relative_to_assets("entry_3.png"))
    entry_bg_3 = canvas.create_image(
        302.5,
        246.0,
        image=entry_image_3
    )
    entry_3 = Entry(canvas,
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_3.place(
        x=117.0,
        y=225.0,
        width=371.0,
        height=40.0
    )

    entry_image_4 = PhotoImage(
        file=relative_to_assets("entry_4.png"))
    entry_bg_4 = canvas.create_image(
        253.5,
        420.0,
        image=entry_image_4
    )
    entry_4 = Text(canvas,
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_4.place(
        x=5.0,
        y=286.0,
        width=497.0,
        height=266.0
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(canvas,
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=SendEmail,
        relief="flat"
    )
    button_1.place(
        x=418.0,
        y=570.0,
        width=68.0,
        height=36.0
    )
    window.resizable(False, False)
    window.mainloop()
