
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import tkinter as tk
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C://Users/keray/Unity3d/Interactionhuman/Virtual_Assistant/MainGui/assets_6/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def SendMessage():
    receiver = entry_1.get()
    if not receiver:
        messagebox.showerror('Error','Message has not been send')
    else:
        messagebox.showinfo('','Message has been sent')



def SMS():
    window = tk.Toplevel()

    window.geometry("526x600")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 600,
        width = 526,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        0.0,
        78.0,
        526.0,
        600.0,
        fill="#D9D9D9",
        outline="")

    canvas.create_text(
        0.0,
        84.0,
        anchor="nw",
        text="To: ",
        fill="#000000",
        font=("Comfortaa Regular", 24 * -1)
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(canvas,
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=SendMessage,
        relief="flat"
    )
    button_1.place(
        x=463.0,
        y=549.0,
        width=61.0,
        height=49.0
    )

    canvas.create_rectangle(
        0.0,
        0.0,
        526.0,
        78.0,
        fill="#45728B",
        outline="")

    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        263.0,
        39.0,
        image=image_image_1
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        178.0,
        101.0,
        image=entry_image_1
    )
    global entry_1
    entry_1 = Entry(canvas,
        bd=0,
        bg="#C8D9D7",
        fg="#000716",
        highlightthickness=0,
        font=('Comfortaa',18,'bold')
    )
    entry_1.place(
        x=48.0,
        y=81.0,
        width=260.0,
        height=38.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        263.0,
        346.5,
        image=entry_image_2
    )
    entry_2 = Text(canvas,
        bd=0,
        bg="#C8D8D6",
        fg="#000716",
        highlightthickness=0,
        font=('Comfortaa',16)
    )
    entry_2.place(
        x=0.0,
        y=159.0,
        width=526.0,
        height=373.0
    )
    window.resizable(False, False)
    window.mainloop()
